<?php

use Illuminate\Database\Seeder;
use App\Models\Coaching\CoachingSection;
class SectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        CoachingSection::insert([
        	[
        		'name' => 'B-011',
        		'gender' => 'Male',
        		'start_time' => '01:01:00 pm',
        		'end_time' => '01:01:00 pm',
        		'type' => 'regular',
        		'class' => '1',
        		'hint' => 'both are allowd ',
        		'inst_identity' => 601,
        	],
        	[
        		'name' => 'B-012',
        		'gender' => 'Female',
        		'start_time' => '01:01:00 pm',
        		'end_time' => '01:01:00 pm',
        		'type' => 'regular',
        		'class' => '1',
        		'hint' => 'only female ',
        		'inst_identity' => 601,
        	],


            [
                'name' => 'B-023',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '2',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-024',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '2',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-035',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '3',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-036',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '3',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-047',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '4',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-048',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '4',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-059',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '5',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-0510',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '5',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-0611',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '6',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-0612',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '6',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-0713',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '7',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-0714',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '7',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-0815',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '8',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-0816',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '8',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-0917',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '9',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-0918',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '9',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-1019',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '10',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-1020',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '10',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-1121',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '11',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-1122',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '11',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],

            [
                'name' => 'B-1223',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '12',
                'hint' => 'both are allowd ',
                'inst_identity' => 601,
            ],
            [
                'name' => 'B-1224',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '12',
                'hint' => 'only female ',
                'inst_identity' => 601,
            ],





            [
                'name' => 'B-011',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '1',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-012',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '1',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],


            [
                'name' => 'B-023',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '2',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-024',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '2',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-035',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '3',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-036',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '3',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-047',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '4',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-048',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '4',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-059',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '5',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-0510',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '5',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-0611',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '6',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-0612',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '6',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-0713',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '7',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-0714',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '7',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-0815',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '8',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-0816',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '8',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-0917',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '9',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-0918',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '9',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-1019',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '10',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-1020',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '10',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-1121',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '11',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-1122',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '11',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],

            [
                'name' => 'B-1223',
                'gender' => 'Male',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '12',
                'hint' => 'both are allowd ',
                'inst_identity' => 602,
            ],
            [
                'name' => 'B-1224',
                'gender' => 'Female',
                'start_time' => '01:01:00 pm',
                'end_time' => '01:01:00 pm',
                'type' => 'regular',
                'class' => '12',
                'hint' => 'only female ',
                'inst_identity' => 602,
            ],
        ]);
    }
}
